// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func BuildDependencies() (*PersonService, error) {
	config := NewConfig()
	db := NewDB()
	personRepository := NewPersonRepository(config, db)
	personService := NewPersonService(config, personRepository)
	return personService, nil
}
